# Generated by Django 5.2.8 on 2025-11-23 05:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('tecnologia', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('administrador', models.CharField(max_length=255)),
            ],
        ),
    ]
