# Generated by Django 5.2.8 on 2025-11-23 06:52

from django.db import migrations

def crear_zona_la_perla(apps, schema_editor):
    Zona = apps.get_model('vigilancia', 'Zona')
    Zona.objects.create(nombre="La Perla")

class Migration(migrations.Migration):

    dependencies = [
        ('vigilancia', '0002_zona'),
    ]

    operations = [
        migrations.RunPython(crear_zona_la_perla),
    ]
