# Generated by Django 5.2.8 on 2025-11-23 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilancia', '0003_crear_zona_por_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='zona',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vigilancia.zona'),
        ),
    ]
