# Generated by Django 5.2.8 on 2025-11-25 22:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilancia', '0004_camara_zona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camara',
            options={'ordering': ['-id'], 'verbose_name': 'Cámara', 'verbose_name_plural': 'Cámaras'},
        ),
        migrations.AddField(
            model_name='camara',
            name='estado',
            field=models.CharField(choices=[('operativa', 'Operativa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En Mantenimiento')], default='operativa', max_length=20),
        ),
        migrations.AddField(
            model_name='camara',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camara',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fallo_tecnico', 'Fallo Técnico'), ('mantenimiento', 'Mantenimiento Programado'), ('vandalismo', 'Vandalismo'), ('desconexion', 'Desconexión'), ('alerta', 'Alerta de Seguridad'), ('otro', 'Otro')], max_length=20)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_atencion', 'En Atención'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=15)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('reportado_por', models.CharField(blank=True, max_length=100)),
                ('atendido_por', models.CharField(blank=True, max_length=100, null=True)),
                ('notas_resolucion', models.TextField(blank=True, null=True)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='vigilancia.camara')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
