--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg110+1)
-- Dumped by pg_dump version 15.4 (Debian 15.4-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tiger; Type: SCHEMA; Schema: -; Owner: calidad_user
--

CREATE SCHEMA tiger;


ALTER SCHEMA tiger OWNER TO calidad_user;

--
-- Name: tiger_data; Type: SCHEMA; Schema: -; Owner: calidad_user
--

CREATE SCHEMA tiger_data;


ALTER SCHEMA tiger_data OWNER TO calidad_user;

--
-- Name: topology; Type: SCHEMA; Schema: -; Owner: calidad_user
--

CREATE SCHEMA topology;


ALTER SCHEMA topology OWNER TO calidad_user;

--
-- Name: SCHEMA topology; Type: COMMENT; Schema: -; Owner: calidad_user
--

COMMENT ON SCHEMA topology IS 'PostGIS Topology schema';


--
-- Name: fuzzystrmatch; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS fuzzystrmatch WITH SCHEMA public;


--
-- Name: EXTENSION fuzzystrmatch; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION fuzzystrmatch IS 'determine similarities and distance between strings';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: postgis_tiger_geocoder; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder WITH SCHEMA tiger;


--
-- Name: EXTENSION postgis_tiger_geocoder; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis_tiger_geocoder IS 'PostGIS tiger geocoder and reverse geocoder';


--
-- Name: postgis_topology; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;


--
-- Name: EXTENSION postgis_topology; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis_topology IS 'PostGIS topology spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO calidad_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO calidad_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO calidad_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO calidad_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO calidad_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO calidad_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO calidad_user;

--
-- Name: rutas_ruta; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.rutas_ruta (
    id bigint NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    linea public.geometry(LineString,4326) NOT NULL
);


ALTER TABLE public.rutas_ruta OWNER TO calidad_user;

--
-- Name: rutas_ruta_camaras; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.rutas_ruta_camaras (
    id bigint NOT NULL,
    ruta_id bigint NOT NULL,
    camara_id bigint NOT NULL
);


ALTER TABLE public.rutas_ruta_camaras OWNER TO calidad_user;

--
-- Name: rutas_ruta_camaras_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.rutas_ruta_camaras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rutas_ruta_camaras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rutas_ruta_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.rutas_ruta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rutas_ruta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.usuarios_usuario (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    id_usuario integer NOT NULL,
    nombre character varying(150) NOT NULL,
    rol character varying(50) NOT NULL
);


ALTER TABLE public.usuarios_usuario OWNER TO calidad_user;

--
-- Name: usuarios_usuario_groups; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.usuarios_usuario_groups (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.usuarios_usuario_groups OWNER TO calidad_user;

--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.usuarios_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.usuarios_usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_user_permissions; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.usuarios_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.usuarios_usuario_user_permissions OWNER TO calidad_user;

--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.usuarios_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vigilancia_camara; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.vigilancia_camara (
    id bigint NOT NULL,
    direccion character varying(255) NOT NULL,
    tecnologia character varying(50) NOT NULL,
    tipo character varying(50) NOT NULL,
    marca character varying(50) NOT NULL,
    ubicacion public.geometry(Point,4326) NOT NULL,
    administrador character varying(255) NOT NULL,
    zona_id bigint,
    estado character varying(20) NOT NULL,
    fecha_instalacion date,
    observaciones text
);


ALTER TABLE public.vigilancia_camara OWNER TO calidad_user;

--
-- Name: vigilancia_camara_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.vigilancia_camara ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vigilancia_camara_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vigilancia_evento; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.vigilancia_evento (
    id bigint NOT NULL,
    tipo character varying(20) NOT NULL,
    severidad character varying(10) NOT NULL,
    estado character varying(15) NOT NULL,
    titulo character varying(200) NOT NULL,
    descripcion text NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    fecha_resolucion timestamp with time zone,
    reportado_por character varying(100) NOT NULL,
    atendido_por character varying(100),
    notas_resolucion text,
    camara_id bigint NOT NULL
);


ALTER TABLE public.vigilancia_evento OWNER TO calidad_user;

--
-- Name: vigilancia_evento_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.vigilancia_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vigilancia_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vigilancia_zona; Type: TABLE; Schema: public; Owner: calidad_user
--

CREATE TABLE public.vigilancia_zona (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.vigilancia_zona OWNER TO calidad_user;

--
-- Name: vigilancia_zona_id_seq; Type: SEQUENCE; Schema: public; Owner: calidad_user
--

ALTER TABLE public.vigilancia_zona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vigilancia_zona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add usuario	6	add_usuario
22	Can change usuario	6	change_usuario
23	Can delete usuario	6	delete_usuario
24	Can view usuario	6	view_usuario
25	Can add Cámara	7	add_camara
26	Can change Cámara	7	change_camara
27	Can delete Cámara	7	delete_camara
28	Can view Cámara	7	view_camara
29	Can add zona	8	add_zona
30	Can change zona	8	change_zona
31	Can delete zona	8	delete_zona
32	Can view zona	8	view_zona
33	Can add Evento	9	add_evento
34	Can change Evento	9	change_evento
35	Can delete Evento	9	delete_evento
36	Can view Evento	9	view_evento
37	Can add ruta	10	add_ruta
38	Can change ruta	10	change_ruta
39	Can delete ruta	10	delete_ruta
40	Can view ruta	10	view_ruta
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	usuarios	usuario
7	vigilancia	camara
8	vigilancia	zona
9	vigilancia	evento
10	rutas	ruta
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-11-27 18:31:48.031119+00
2	contenttypes	0002_remove_content_type_name	2025-11-27 18:31:48.041131+00
3	auth	0001_initial	2025-11-27 18:31:48.110222+00
4	auth	0002_alter_permission_name_max_length	2025-11-27 18:31:48.116915+00
5	auth	0003_alter_user_email_max_length	2025-11-27 18:31:48.12377+00
6	auth	0004_alter_user_username_opts	2025-11-27 18:31:48.130898+00
7	auth	0005_alter_user_last_login_null	2025-11-27 18:31:48.13802+00
8	auth	0006_require_contenttypes_0002	2025-11-27 18:31:48.141313+00
9	auth	0007_alter_validators_add_error_messages	2025-11-27 18:31:48.148327+00
10	auth	0008_alter_user_username_max_length	2025-11-27 18:31:48.156898+00
11	auth	0009_alter_user_last_name_max_length	2025-11-27 18:31:48.163873+00
12	auth	0010_alter_group_name_max_length	2025-11-27 18:31:48.173078+00
13	auth	0011_update_proxy_permissions	2025-11-27 18:31:48.181148+00
14	auth	0012_alter_user_first_name_max_length	2025-11-27 18:31:48.188099+00
15	usuarios	0001_initial	2025-11-27 18:31:48.265972+00
16	admin	0001_initial	2025-11-27 18:31:48.299907+00
17	admin	0002_logentry_remove_auto_add	2025-11-27 18:31:48.308463+00
18	admin	0003_logentry_add_action_flag_choices	2025-11-27 18:31:48.31826+00
19	vigilancia	0001_initial	2025-11-27 18:31:48.348953+00
20	vigilancia	0002_zona	2025-11-27 18:31:48.358446+00
21	vigilancia	0003_crear_zona_por_defecto	2025-11-27 18:31:48.371939+00
22	vigilancia	0004_camara_zona	2025-11-27 18:31:48.386586+00
23	rutas	0001_initial	2025-11-27 18:31:48.433608+00
24	sessions	0001_initial	2025-11-27 18:31:48.459557+00
25	usuarios	0002_alter_usuario_options_alter_usuario_managers_and_more	2025-11-27 18:31:48.570973+00
26	vigilancia	0005_alter_camara_options_camara_estado_and_more	2025-11-27 18:31:48.608975+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: rutas_ruta; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.rutas_ruta (id, nombre, descripcion, fecha_creacion, linea) FROM stdin;
\.


--
-- Data for Name: rutas_ruta_camaras; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.rutas_ruta_camaras (id, ruta_id, camara_id) FROM stdin;
\.


--
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- Data for Name: usuarios_usuario; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.usuarios_usuario (password, last_login, is_superuser, email, is_staff, is_active, date_joined, id_usuario, nombre, rol) FROM stdin;
\.


--
-- Data for Name: usuarios_usuario_groups; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.usuarios_usuario_groups (id, usuario_id, group_id) FROM stdin;
\.


--
-- Data for Name: usuarios_usuario_user_permissions; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.usuarios_usuario_user_permissions (id, usuario_id, permission_id) FROM stdin;
\.


--
-- Data for Name: vigilancia_camara; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.vigilancia_camara (id, direccion, tecnologia, tipo, marca, ubicacion, administrador, zona_id, estado, fecha_instalacion, observaciones) FROM stdin;
\.


--
-- Data for Name: vigilancia_evento; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.vigilancia_evento (id, tipo, severidad, estado, titulo, descripcion, fecha_registro, fecha_resolucion, reportado_por, atendido_por, notas_resolucion, camara_id) FROM stdin;
\.


--
-- Data for Name: vigilancia_zona; Type: TABLE DATA; Schema: public; Owner: calidad_user
--

COPY public.vigilancia_zona (id, nombre) FROM stdin;
1	La Perla
\.


--
-- Data for Name: geocode_settings; Type: TABLE DATA; Schema: tiger; Owner: calidad_user
--

COPY tiger.geocode_settings (name, setting, unit, category, short_desc) FROM stdin;
\.


--
-- Data for Name: pagc_gaz; Type: TABLE DATA; Schema: tiger; Owner: calidad_user
--

COPY tiger.pagc_gaz (id, seq, word, stdword, token, is_custom) FROM stdin;
\.


--
-- Data for Name: pagc_lex; Type: TABLE DATA; Schema: tiger; Owner: calidad_user
--

COPY tiger.pagc_lex (id, seq, word, stdword, token, is_custom) FROM stdin;
\.


--
-- Data for Name: pagc_rules; Type: TABLE DATA; Schema: tiger; Owner: calidad_user
--

COPY tiger.pagc_rules (id, rule, is_custom) FROM stdin;
\.


--
-- Data for Name: topology; Type: TABLE DATA; Schema: topology; Owner: calidad_user
--

COPY topology.topology (id, name, srid, "precision", hasz) FROM stdin;
\.


--
-- Data for Name: layer; Type: TABLE DATA; Schema: topology; Owner: calidad_user
--

COPY topology.layer (topology_id, layer_id, schema_name, table_name, feature_column, feature_type, level, child_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 26, true);


--
-- Name: rutas_ruta_camaras_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.rutas_ruta_camaras_id_seq', 1, false);


--
-- Name: rutas_ruta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.rutas_ruta_id_seq', 1, false);


--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.usuarios_usuario_groups_id_seq', 1, false);


--
-- Name: usuarios_usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.usuarios_usuario_id_usuario_seq', 1, false);


--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.usuarios_usuario_user_permissions_id_seq', 1, false);


--
-- Name: vigilancia_camara_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.vigilancia_camara_id_seq', 1, false);


--
-- Name: vigilancia_evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.vigilancia_evento_id_seq', 1, false);


--
-- Name: vigilancia_zona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: calidad_user
--

SELECT pg_catalog.setval('public.vigilancia_zona_id_seq', 1, true);


--
-- Name: topology_id_seq; Type: SEQUENCE SET; Schema: topology; Owner: calidad_user
--

SELECT pg_catalog.setval('topology.topology_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: rutas_ruta_camaras rutas_ruta_camaras_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.rutas_ruta_camaras
    ADD CONSTRAINT rutas_ruta_camaras_pkey PRIMARY KEY (id);


--
-- Name: rutas_ruta_camaras rutas_ruta_camaras_ruta_id_camara_id_70b1bfbe_uniq; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.rutas_ruta_camaras
    ADD CONSTRAINT rutas_ruta_camaras_ruta_id_camara_id_70b1bfbe_uniq UNIQUE (ruta_id, camara_id);


--
-- Name: rutas_ruta rutas_ruta_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.rutas_ruta
    ADD CONSTRAINT rutas_ruta_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario usuarios_usuario_email_0a82e5f9_uniq; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_email_0a82e5f9_uniq UNIQUE (email);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq UNIQUE (usuario_id, group_id);


--
-- Name: usuarios_usuario usuarios_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq UNIQUE (usuario_id, permission_id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: vigilancia_camara vigilancia_camara_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.vigilancia_camara
    ADD CONSTRAINT vigilancia_camara_pkey PRIMARY KEY (id);


--
-- Name: vigilancia_evento vigilancia_evento_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.vigilancia_evento
    ADD CONSTRAINT vigilancia_evento_pkey PRIMARY KEY (id);


--
-- Name: vigilancia_zona vigilancia_zona_pkey; Type: CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.vigilancia_zona
    ADD CONSTRAINT vigilancia_zona_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: rutas_ruta_camaras_camara_id_52aa22a7; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX rutas_ruta_camaras_camara_id_52aa22a7 ON public.rutas_ruta_camaras USING btree (camara_id);


--
-- Name: rutas_ruta_camaras_ruta_id_4a28d17e; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX rutas_ruta_camaras_ruta_id_4a28d17e ON public.rutas_ruta_camaras USING btree (ruta_id);


--
-- Name: rutas_ruta_linea_2dd8eb36_id; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX rutas_ruta_linea_2dd8eb36_id ON public.rutas_ruta USING gist (linea);


--
-- Name: usuarios_usuario_email_0a82e5f9_like; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX usuarios_usuario_email_0a82e5f9_like ON public.usuarios_usuario USING btree (email varchar_pattern_ops);


--
-- Name: usuarios_usuario_groups_group_id_e77f6dcf; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX usuarios_usuario_groups_group_id_e77f6dcf ON public.usuarios_usuario_groups USING btree (group_id);


--
-- Name: usuarios_usuario_groups_usuario_id_7a34077f; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX usuarios_usuario_groups_usuario_id_7a34077f ON public.usuarios_usuario_groups USING btree (usuario_id);


--
-- Name: usuarios_usuario_user_permissions_permission_id_4e5c0f2f; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX usuarios_usuario_user_permissions_permission_id_4e5c0f2f ON public.usuarios_usuario_user_permissions USING btree (permission_id);


--
-- Name: usuarios_usuario_user_permissions_usuario_id_60aeea80; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX usuarios_usuario_user_permissions_usuario_id_60aeea80 ON public.usuarios_usuario_user_permissions USING btree (usuario_id);


--
-- Name: vigilancia_camara_ubicacion_c731b738_id; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX vigilancia_camara_ubicacion_c731b738_id ON public.vigilancia_camara USING gist (ubicacion);


--
-- Name: vigilancia_camara_zona_id_13025237; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX vigilancia_camara_zona_id_13025237 ON public.vigilancia_camara USING btree (zona_id);


--
-- Name: vigilancia_evento_camara_id_c14fc31b; Type: INDEX; Schema: public; Owner: calidad_user
--

CREATE INDEX vigilancia_evento_camara_id_c14fc31b ON public.vigilancia_evento USING btree (camara_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: rutas_ruta_camaras rutas_ruta_camaras_camara_id_52aa22a7_fk_vigilancia_camara_id; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.rutas_ruta_camaras
    ADD CONSTRAINT rutas_ruta_camaras_camara_id_52aa22a7_fk_vigilancia_camara_id FOREIGN KEY (camara_id) REFERENCES public.vigilancia_camara(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: rutas_ruta_camaras rutas_ruta_camaras_ruta_id_4a28d17e_fk_rutas_ruta_id; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.rutas_ruta_camaras
    ADD CONSTRAINT rutas_ruta_camaras_ruta_id_4a28d17e_fk_rutas_ruta_id FOREIGN KEY (ruta_id) REFERENCES public.rutas_ruta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vigilancia_camara vigilancia_camara_zona_id_13025237_fk_vigilancia_zona_id; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.vigilancia_camara
    ADD CONSTRAINT vigilancia_camara_zona_id_13025237_fk_vigilancia_zona_id FOREIGN KEY (zona_id) REFERENCES public.vigilancia_zona(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vigilancia_evento vigilancia_evento_camara_id_c14fc31b_fk_vigilancia_camara_id; Type: FK CONSTRAINT; Schema: public; Owner: calidad_user
--

ALTER TABLE ONLY public.vigilancia_evento
    ADD CONSTRAINT vigilancia_evento_camara_id_c14fc31b_fk_vigilancia_camara_id FOREIGN KEY (camara_id) REFERENCES public.vigilancia_camara(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

