# Generated by Django 5.2.8 on 2025-11-23 23:14

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigilancia', '0004_camara_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('linea', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('camaras', models.ManyToManyField(blank=True, related_name='rutas', to='vigilancia.camara')),
            ],
        ),
    ]
